spring.application.name=Task6
spring.datasource.url=jdbc:mysql://localhost:3306/testapi
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.security.user.name=bia
spring.security.user.password=1234